[platformio]
default_envs = cardputer-adv

[env:cardputer-adv]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
board_build.flash_size = 8MB
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -O3
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    https://github.com/m5stack/M5Cardputer.git#1.2.0

